use_frameworks!

inhibit_all_warnings!

target 'FlexBoxSupport_Example' do
  pod 'FlexBoxSupport', :path => '../'
  pod 'PinLayout', '1.7.9'
  pod 'Kingfisher', '~> 4.8.0'
  
  pod 'LookinServer', :configurations => ['Debug']
  
end
